import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:site_board/core/common/widgets/loader.dart';
import 'package:site_board/core/utils/show_snackbar.dart';
import 'package:site_board/feature/auth/presentation/bloc/auth_bloc.dart';

import '../../../core/common/entities/user.dart';
import '../../../core/common/widgets/default_button.dart';
import '../../projectSection/domain/entities/Member.dart';
import '../../projectSection/domain/entities/project.dart';
import '../../projectSection/presentation/bloc/project_bloc.dart';
import '../../projectSection/presentation/pages/project_home_page.dart';
import '../../projectSection/presentation/widgets/main_alert_dialog.dart';
import '../../projectSection/presentation/widgets/project_list_item.dart';
import '../../projectSection/presentation/widgets/text_with_prefix.dart';

class AccountPage extends StatefulWidget {
  final User user;
  static route({required User user}) =>
      MaterialPageRoute(builder: (context) => AccountPage(user: user));
  const AccountPage({required this.user, super.key});

  @override
  State<AccountPage> createState() => _AccountPageState();
}

class _AccountPageState extends State<AccountPage> {
  @override
  void initState() {
    context.read<ProjectBloc>().add(
      ProjectGetAllProjects(userId: widget.user.id),
    );
    super.initState();
  }

  void _updateCreatorStatus(Project project) {
    Member? soughtMember;

    // Attempt to find the user in the team members list
    for (var member in project.teamMembers) {
      if (member.userId == widget.user.id) {
        soughtMember = member;
        break;
      }
    }

    // FIX ISSUE E: Null check before access
    if (soughtMember != null) {
      context.read<ProjectBloc>().add(
        UpdateMemberEvent(
          project: project,
          member: soughtMember.copyWith(lastViewed: DateTime.now()),
          isCreateMember: false,
        ),
      );
    } else {
      // User is the creator/viewer but not in the member list.
      // This might happen if they are viewing a public project or syncing issues.
      // For now, we can try to "create" the member if they are the creator,
      // or just open the project without updating stats to avoid crash.

      if (project.creatorId == widget.user.id) {
        // If creator, we can trigger an update to add them
        context.read<ProjectBloc>().add(
          UpdateMemberEvent(
            project: project,
            member: Member(
              id: "", // ID will be generated by repo/server
              projectId: project.id,
              name: widget.user.name,
              email: widget.user.email,
              userId: widget.user.id,
              isAccepted: true,
              isBlocked: false,
              isAdmin: true,
              hasLeft: false,
              lastViewed: DateTime.now(),
            ),
            isCreateMember: true,
          ),
        );
      } else {
        // Just open it
        Navigator.push(
          context,
          ProjectHomePage.route(
            project: project,
            projectIndex: 0, // Index logic handled in Bloc or not needed here
            isLocal: false,
          ),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Profile', style: TextStyle(fontWeight: FontWeight.bold)),
        actions: [],
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: BlocListener<AuthBloc, AuthState>(
          listener: (context, state) {
            if (state is AuthFailure) {
              showSnackBar(context, state.message);
              Navigator.pop(context);
            }
          },
          child: Column(
            mainAxisAlignment: MainAxisAlignment.start,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              SizedBox(height: 20),
              TextWithPrefix(
                prefix: 'Name',
                text: widget.user.name,
                textSize: 16,
              ),
              SizedBox(height: 16),
              TextWithPrefix(
                prefix: 'Email',
                text: widget.user.email,
                textSize: 16,
              ),

              SizedBox(height: 16),
              Divider(),
              SizedBox(height: 8),
              Text(
                'Created Projects',
                style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
              ),
              SizedBox(height: 16),
              BlocConsumer<ProjectBloc, ProjectState>(
                listener: (context, state) {
                  if (state is ProjectLoading) {
                    showLoaderDialog(context);
                  }
                  if (state is ProjectRetrieveSuccess ||
                      state is ProjectFailure) {
                    Navigator.of(context, rootNavigator: true).pop();
                  }
                  if (state is ProjectMemberUpdateFailure) {
                    Navigator.of(context, rootNavigator: true).pop();
                    showDialog(
                      context: context,
                      builder:
                          (context) => MainAlertDialog(
                        title: 'Error Loading Project',
                        text:
                        '${state.error}\n\nWe encountered an error while trying to retrieve data from this project.',
                        onDismiss: () {
                          Navigator.pop(context);
                        },
                      ),
                    );
                  }
                  if (state is ProjectMemberUpdateSuccess) {
                    context.read<ProjectBloc>().add(
                      ProjectAddToRecent(project: state.project),
                    );
                  }
                  if (state is ProjectRetrieveAddRecent) {
                    Navigator.of(context, rootNavigator: true).pop();
                    Navigator.push(
                      context,
                      ProjectHomePage.route(
                        project: state.project,
                        projectIndex: state.projects.indexOf(state.project),
                        isLocal: false,
                      ),
                    );
                  }
                },
                builder: (context, state) {
                  if (state is ProjectFailure) {
                    return GestureDetector(
                      onTap: () {
                        context.read<ProjectBloc>().add(
                          ProjectGetAllProjects(userId: widget.user.id),
                        );
                      },
                      child: Text(
                        'Not connected to the internet. Click to retry.',
                        style: TextStyle(fontSize: 16),
                        textAlign: TextAlign.center,
                      ),
                    );
                  }

                  if (state is ProjectRetrieveSuccess) {
                    return state.projects.isEmpty
                        ? SizedBox(
                      height: 120,
                      child: Center(child: Text("No projects found.")),
                    )
                        : Column(
                      children:
                      state.projects.map((project) {
                        return ProjectListItem(
                          projectName: project.projectName,
                          onClicked: () {
                            _updateCreatorStatus(project);
                          },
                        );
                      }).toList(),
                    );
                  }

                  return SizedBox.shrink();
                },
              ),

              SizedBox(height: 16),
              Text(
                'Sign Out',
                style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
              ),
              SizedBox(height: 16),
              Text(
                'Signing out will remove your data from this device. You can access your account again on this or any other device by logging back in.',
                style: TextStyle(fontSize: 16),
              ),
              SizedBox(height: 16),
              DefaultButton(
                onClick: () {
                  context.read<AuthBloc>().add(AuthLogout());
                },
                text: 'Sign out',
              ),
              SizedBox(height: 16),
              Divider(),
              SizedBox(height: 16),
              Text(
                'Delete Account',
                style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
              ),
              SizedBox(height: 16),
              Text(
                'Deleting your account will permanently remove your personal data, including your name and email. You will lose access to all connected projects. Projects you created will remain if they have other participants. You may choose to delete them before proceeding.',
                style: TextStyle(fontSize: 16),
              ),
              SizedBox(height: 16),
              DefaultButton(onClick: () {}, text: 'Delete'),
            ],
          ),
        ),
      ),
    );
  }
}