import 'package:flutter/foundation.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:site_board/feature/projectSection/domain/entities/material_transaction.dart';
import 'package:site_board/feature/projectSection/domain/entities/project_material.dart';
import 'package:site_board/feature/projectSection/domain/repositories/inventory_repository.dart';
import 'package:uuid/uuid.dart';

part 'inventory_event.dart';
part 'inventory_state.dart';

class InventoryBloc extends Bloc<InventoryEvent, InventoryState> {
  final InventoryRepository _inventoryRepository;

  InventoryBloc({required InventoryRepository inventoryRepository})
    : _inventoryRepository = inventoryRepository,
      super(InventoryInitial()) {
    on<InventoryGetMaterials>(_onGetMaterials);
    on<InventoryCreateMaterial>(_onCreateMaterial);
    on<InventoryRestockMaterial>(_onRestockMaterial);
    on<InventoryUseMaterial>(_onUseMaterial);
    on<InventoryBatchUseMaterial>(_onBatchUseMaterial);
    on<InventoryGetTransactions>(_onGetTransactions);
  }

  Future<void> _onGetTransactions(
    InventoryGetTransactions event,
    Emitter<InventoryState> emit,
  ) async {
    emit(InventoryLoading());
    final result = await _inventoryRepository.getTransactions(
      projectId: event.projectId,
    );
    result.fold(
      (failure) => emit(InventoryFailure(failure.message)),
      (transactions) => emit(InventoryTransactionsLoaded(transactions)),
    );
  }

  Future<void> _onGetMaterials(
    InventoryGetMaterials event,
    Emitter<InventoryState> emit,
  ) async {
    emit(InventoryLoading());
    final result = await _inventoryRepository.getMaterials(
      projectId: event.projectId,
    );
    result.fold(
      (failure) => emit(InventoryFailure(failure.message)),
      (materials) => emit(InventoryMaterialsLoaded(materials)),
    );
  }

  Future<void> _onCreateMaterial(
    InventoryCreateMaterial event,
    Emitter<InventoryState> emit,
  ) async {
    emit(InventoryLoading());

    // Create entity (ID and CreatedAt handled by DB/Model mapping usually, but
    // for domain entity creation we can pass placeholders or let Repository handle it.
    // Our Repo implementation uses ProjectMaterialModel.fromEntity, so we need to valid entity.
    // However, the ID is usually generated by DB if not provided, but our Entity constructor requires ID.
    // For now, we'll pass an empty ID and let the Repo/datasource ignore it or handle it.
    // Actually, looking at Phase 1 code, ProjectMaterial constructor requires ID.
    // But in `inventory_remote_data_source`, `createMaterial` does `insert(material.toJson())`.
    // And `ProjectMaterialModel.toJson()` includes 'id' if present.
    // Supabase usually ignores ID on insert if it's explicitly generated defaults,
    // OR we can generate a UUID here.

    // Better approach: Let's assume we are passing a UUID generic or let the Data Layer exclude it if empty.
    // The previous implementation of ProjectMaterialModel includes ID.
    // Let's generate a temporary ID here just to satisfy the Entity,
    // but relies on DB default if appropriate or use `Uuid` package.
    // To keep it clean, I'll pass an empty string for now and rely on RemoteSource to handle it
    // or arguably better, I should have imported Uuid in the bloc.
    // Let's check imports. I'll stick to a simple empty string for ID,
    // but the `ProjectMaterialModel.toJson` sends it.
    // If Supabase sees an empty string UUID it might fail.
    // I will exclude 'id' from toJson if it's empty in best practice,
    // but I can't change the model right now without a tool call.
    //
    // Wait, the user plan phase 1 is done.
    // `ProjectMaterial` entity requires ID.
    // Let's just give it a placeholder like 'new' and hope Supabase ignores it
    // or expects the backend to generate it.
    // Actually, `InventoryRemoteDataSourceImpl` `insert(material.toJson())`.
    // `ProjectMaterialModel.toJson` sends 'id'.
    // If I send a fake ID, Supabase looks for it? No, if it's a primary key, it tries to insert it.
    // It's defined as `default gen_random_uuid()` in SQL.
    // If I send a valid UUID, it uses it.
    // Codebase uses `uuid` package elsewhere. I should use it if possible.
    // I'll skip importing uuid package for now to save complexity and use a specific "create-new"
    // strategy if needed, OR just trust `InventoryRepositoryImpl` handles it?
    // `InventoryRepositoryImpl` takes `ProjectMaterial`.
    // I will pass a dummy ID and assume I might need to fix the Model to ignore empty IDs.
    // CHECK: `uuid` is in pubspec.yaml. I should use it.

    // Changing approach: I will let the UI generated a UUID for safety and consistency,
    // or I will add it here.

    final newMaterial = ProjectMaterial(
      id: const Uuid().v4(),
      projectId: event.projectId,
      name: event.name,
      unit: event.unit,
      currentQuantity: 0,
      createdAt: DateTime.now(),
    );

    final result = await _inventoryRepository.createMaterial(
      material: newMaterial,
    );

    await result.fold(
      (failure) async => emit(InventoryFailure(failure.message)),
      (material) async {
        // Refresh list to include new item (merged by repo)
        final refreshResult = await _inventoryRepository.getMaterials(
          projectId: event.projectId,
        );
        refreshResult.fold(
          (failure) => emit(InventoryFailure(failure.message)),
          (materials) => emit(
            InventoryMaterialsLoaded(
              materials,
              message: 'Material "${material.name}" created',
            ),
          ),
        );
      },
    );
  }

  Future<void> _onRestockMaterial(
    InventoryRestockMaterial event,
    Emitter<InventoryState> emit,
  ) async {
    // We don't want to wipe the list, so we might want to keep the current state if possible?
    // But for simplicity, let's show loading then refresh.
    emit(InventoryLoading());
    final result = await _inventoryRepository.restockMaterial(
      materialId: event.materialId,
      quantity: event.quantity,
      unitPrice: event.unitPrice,
      actorId: event.actorId,
      note: event.note,
    );

    await result.fold(
      (failure) async => emit(InventoryFailure(failure.message)),
      (_) async {
        final refreshResult = await _inventoryRepository.getMaterials(
          projectId: event.projectId,
        );
        refreshResult.fold(
          (failure) => emit(InventoryFailure(failure.message)),
          (materials) => emit(
            InventoryMaterialsLoaded(
              materials,
              message: 'Stock updated successfully',
            ),
          ),
        );
      },
    );
  }

  Future<void> _onUseMaterial(
    InventoryUseMaterial event,
    Emitter<InventoryState> emit,
  ) async {
    emit(InventoryLoading());
    final result = await _inventoryRepository.useMaterial(
      materialId: event.materialId,
      quantity: event.quantity,
      dailyLogId: event.dailyLogId,
      actorId: event.actorId,
    );

    await result.fold(
      (failure) async => emit(InventoryFailure(failure.message)),
      (_) async {
        final refreshResult = await _inventoryRepository.getMaterials(
          projectId: event.projectId,
        );
        refreshResult.fold(
          (failure) => emit(InventoryFailure(failure.message)),
          (materials) => emit(
            InventoryMaterialsLoaded(
              materials,
              message: 'Material usage recorded',
            ),
          ),
        );
      },
    );
  }

  Future<void> _onBatchUseMaterial(
    InventoryBatchUseMaterial event,
    Emitter<InventoryState> emit,
  ) async {
    emit(InventoryLoading());
    final result = await _inventoryRepository.useMaterialsBatch(
      usageList: event.usageList,
      dailyLogId: event.dailyLogId,
      actorId: event.actorId,
    );

    await result.fold(
      (failure) async => emit(InventoryFailure(failure.message)),
      (_) async {
        final refreshResult = await _inventoryRepository.getMaterials(
          projectId: event.projectId,
        );
        refreshResult.fold(
          (failure) => emit(InventoryFailure(failure.message)),
          (materials) => emit(
            InventoryMaterialsLoaded(
              materials,
              message: 'Materials usage recorded',
            ),
          ),
        );
      },
    );
  }
}
